/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const FoodType = IDL.Variant({
  'snacks' : IDL.Null,
  'sweets' : IDL.Null,
  'iceCream' : IDL.Null,
  'pastries' : IDL.Null,
  'drinks' : IDL.Null,
});
export const FoodItem = IDL.Record({
  'country' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'imageUrl' : IDL.Opt(IDL.Text),
  'recipeSteps' : IDL.Vec(IDL.Text),
  'foodType' : FoodType,
});

export const idlService = IDL.Service({
  'addFoodItem' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        FoodType,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [],
      [],
    ),
  'filterByCountry' : IDL.Func([IDL.Text], [IDL.Vec(FoodItem)], ['query']),
  'filterByFoodType' : IDL.Func([FoodType], [IDL.Vec(FoodItem)], ['query']),
  'getFoodItem' : IDL.Func([IDL.Text], [FoodItem], ['query']),
  'listAllFoodItems' : IDL.Func([], [IDL.Vec(FoodItem)], ['query']),
  'seedRealData' : IDL.Func([], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const FoodType = IDL.Variant({
    'snacks' : IDL.Null,
    'sweets' : IDL.Null,
    'iceCream' : IDL.Null,
    'pastries' : IDL.Null,
    'drinks' : IDL.Null,
  });
  const FoodItem = IDL.Record({
    'country' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'imageUrl' : IDL.Opt(IDL.Text),
    'recipeSteps' : IDL.Vec(IDL.Text),
    'foodType' : FoodType,
  });
  
  return IDL.Service({
    'addFoodItem' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          FoodType,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [],
        [],
      ),
    'filterByCountry' : IDL.Func([IDL.Text], [IDL.Vec(FoodItem)], ['query']),
    'filterByFoodType' : IDL.Func([FoodType], [IDL.Vec(FoodItem)], ['query']),
    'getFoodItem' : IDL.Func([IDL.Text], [FoodItem], ['query']),
    'listAllFoodItems' : IDL.Func([], [IDL.Vec(FoodItem)], ['query']),
    'seedRealData' : IDL.Func([], [], []),
  });
};

export const init = ({ IDL }) => { return []; };