/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface FoodItem {
    country: string;
    name: string;
    description: string;
    imageUrl?: string;
    recipeSteps: Array<string>;
    foodType: FoodType;
}
export enum FoodType {
    snacks = "snacks",
    sweets = "sweets",
    iceCream = "iceCream",
    pastries = "pastries",
    drinks = "drinks"
}
export interface backendInterface {
    addFoodItem(name: string, country: string, foodType: FoodType, description: string, recipeSteps: Array<string>, imageUrl: string | null): Promise<void>;
    filterByCountry(country: string): Promise<Array<FoodItem>>;
    filterByFoodType(foodType: FoodType): Promise<Array<FoodItem>>;
    getFoodItem(name: string): Promise<FoodItem>;
    listAllFoodItems(): Promise<Array<FoodItem>>;
    seedRealData(): Promise<void>;
}
import type { FoodItem as _FoodItem, FoodType as _FoodType } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addFoodItem(arg0: string, arg1: string, arg2: FoodType, arg3: string, arg4: Array<string>, arg5: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addFoodItem(arg0, arg1, to_candid_FoodType_n1(this._uploadFile, this._downloadFile, arg2), arg3, arg4, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addFoodItem(arg0, arg1, to_candid_FoodType_n1(this._uploadFile, this._downloadFile, arg2), arg3, arg4, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
    async filterByCountry(arg0: string): Promise<Array<FoodItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterByCountry(arg0);
                return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterByCountry(arg0);
            return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async filterByFoodType(arg0: FoodType): Promise<Array<FoodItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterByFoodType(to_candid_FoodType_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterByFoodType(to_candid_FoodType_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFoodItem(arg0: string): Promise<FoodItem> {
        if (this.processError) {
            try {
                const result = await this.actor.getFoodItem(arg0);
                return from_candid_FoodItem_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFoodItem(arg0);
            return from_candid_FoodItem_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async listAllFoodItems(): Promise<Array<FoodItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllFoodItems();
                return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllFoodItems();
            return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async seedRealData(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.seedRealData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.seedRealData();
            return result;
        }
    }
}
function from_candid_FoodItem_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FoodItem): FoodItem {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_FoodType_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FoodType): FoodType {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    country: string;
    name: string;
    description: string;
    imageUrl: [] | [string];
    recipeSteps: Array<string>;
    foodType: _FoodType;
}): {
    country: string;
    name: string;
    description: string;
    imageUrl?: string;
    recipeSteps: Array<string>;
    foodType: FoodType;
} {
    return {
        country: value.country,
        name: value.name,
        description: value.description,
        imageUrl: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.imageUrl)),
        recipeSteps: value.recipeSteps,
        foodType: from_candid_FoodType_n8(_uploadFile, _downloadFile, value.foodType)
    };
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    snacks: null;
} | {
    sweets: null;
} | {
    iceCream: null;
} | {
    pastries: null;
} | {
    drinks: null;
}): FoodType {
    return "snacks" in value ? FoodType.snacks : "sweets" in value ? FoodType.sweets : "iceCream" in value ? FoodType.iceCream : "pastries" in value ? FoodType.pastries : "drinks" in value ? FoodType.drinks : value;
}
function from_candid_vec_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FoodItem>): Array<FoodItem> {
    return value.map((x)=>from_candid_FoodItem_n5(_uploadFile, _downloadFile, x));
}
function to_candid_FoodType_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FoodType): _FoodType {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FoodType): {
    snacks: null;
} | {
    sweets: null;
} | {
    iceCream: null;
} | {
    pastries: null;
} | {
    drinks: null;
} {
    return value == FoodType.snacks ? {
        snacks: null
    } : value == FoodType.sweets ? {
        sweets: null
    } : value == FoodType.iceCream ? {
        iceCream: null
    } : value == FoodType.pastries ? {
        pastries: null
    } : value == FoodType.drinks ? {
        drinks: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
